Navbar creation
cleberMargarida/dotnetflix pull request #4
Opened 2023-02-14 17:04 UTC by vitorbielb

2023-02-14 17:15 UTC, cleberMargarida requested changes

2023-02-14 17:15 UTC, cleberMargarida commented on dotnetflix/Views/Home/Index.cshtml
> -    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
Não precisamos alterar a index. O trabalho da navbar deve ser feito somente no arquivo Layout.cshtml

2023-02-14 17:15 UTC, cleberMargarida commented on dotnetflix/Views/Shared/_Layout.cshtml
> +                .navbar {
Podemos mover tudo o que está na tag Style para o css dotnetflix.styles.css, e então usa-los com o atributo class=".suasclasses"

2023-02-15 18:13 UTC, PauloVitGod12 approved these changes

2023-02-15 18:26 UTC, cleberMargarida approved these changes

2023-02-15 18:37 UTC, closed without merging